### ISSUE TITLE
Look at "synthetic video" and VMHub: do we need new field(s)? a new taxonomy? both?

### ISSUE THREAD

**Issue by bquinn** [iptc/video-metadata-hub#8]
## Use cases:
- e.g. synethsia.io - create video from your own source content.
- content created with Unreal Engine etc
- CGI content in movies and tv - Toy Story etc
- "deepfake" content - generated by software (GAN etc)

## Technologies:
- usually created using GAN or GPT-3 algorithms, but other algorithms will emerge in the future. We probably don't need to know what was the particular algorithm.

### Recording Device:
which has a structure: Manufacturer, Model Name, Serial Number, Attached Lens Description, Owner´s Device ID) - does that fit? Our feeling is no.

### Supplier
Supplier of this copy of the media resource

### Supply Chain Source
Person or party who has a role in the content supply chain.

## What to call the new field? What should be in the taxonomy? spec

"Origin"? "Origination mode"?
- synthetic vs sampled
- Creative aspect?

## Other requirements

The new field(s) / taxonomy/ies should work for both still images and video.

## Other thoughts:
- C2PA has an assertion type `c2pa.actions` which tracks changes made by software after an image has been created. Does this fit somehow?

**Comment by pamfisher** [comment]
[IPTC_VMH_PropertyOrigin.pdf](https://github.com/iptc/video-metadata-hub/files/7206632/IPTC_VMH_PropertyOrigin.pdf)

**Comment by bquinn** [comment]
Discussion today: Do we need to add a field "original source media" or similar? So if we're scanning from film or some other source, people have a place to enter what format the original media used. e.g. super 8 camera, 35mm film etc.

We suggest that "recording device" is the system (hardware/software) that "created the pixels", this might be a scanner or a GAN generator or something else.

**Comment by bquinn** [comment]
Next steps:
1. Come up with a proposed list of new CV terms to add to "Digital Source Type" to cover synthetic media use cases
2. Share with PMD WG and News Architecture WG for review and adding - the idea is that the same CV should cover any media type
3. Submit to NewsCodes WG for finessing definitions and publishing as an update to the NewsCodes vocabulary "Digital Source Type"
4. Look at VM Hub property structures, what fields do we need to add to accommodate this work in the general case?

**Comment by bquinn** [comment]
We have now published a draft version of the new Digital Source Type CV and are soliciting feedback:

https://www.iptc.org/news/iptc-releases-draft-of-digital-source-type-vocabulary-to-support-synthetic-media/
